server:
  port: 1619

eureka:
  instance:
    hostname: 127.0.0.1
  client:
  #是否将自己注册到eureka上,作为消费者的时候要为true
    registerWithEureka: true
    #检索服务
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1616/eureka/

spring:
  application:
    name: order
    
    
      # 心跳检测检测与续约时间   (默认是开启的，但是心跳时间为90s)
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）  
    lease-renewal-interval-in-seconds: 1
####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2    
    
   
    
