server:
  port: 1618

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1616/eureka/
 

spring:
  application:
    name: member
    
swagger:
  base-package: com.dist.member.impl
    
