server:
  port: 1617

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1616/eureka/
      # 集群使用,http://127.0.0.1:1615/eureka/

spring:
  application:
    name: hi
    

    
