server:
  port: 1616

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:1616/eureka/

spring:
  application:
    name: eureka
    
